@HOST=localhost:8080

### healthz
GET http://{{HOST}}/healthz

### registry
POST http://{{HOST}}/registry
Content-Type: application/json

{
    "name": "test1"
}

### get node list
POST http://{{HOST}}/api/node/list

### add node
POST http://{{HOST}}/api/node/add
Content-Type: application/json

{
    "name": "test",
    "address": "127.0.0.1",
    "ssh_port": 22,
    "ssh_user": "root",
    "ssh_password": "password",
    "agent_port": 8080,
    "is_local": true
}

### update node
POST http://{{HOST}}/api/node/update
Content-Type: application/json

{
    "id": 1,
    "name": "test1",
    "address": "127.0.0.1",
    "port": 8080,
    "is_local": true
}

### delete node
POST http://{{HOST}}/api/node/delete
Content-Type: application/json

{
    "id": 1
}

### get node
POST http://{{HOST}}/api/node/get
Content-Type: application/json

{
    "id": 1
}


### get docker info
GET http://{{HOST}}/api/docker/info
Content-Type: application/json
X-Node-ID: 1