@HOST=localhost:8080

### healthz
GET http://{{HOST}}/healthz

### registry
POST http://{{HOST}}/registry
Content-Type: application/json

{
    "name": "test1"
}

### get node list
POST http://{{HOST}}/api/node/list

### add node
POST http://{{HOST}}/api/node/add
Content-Type: application/json

{
    "name": "test",
    "address": "127.0.0.1",
    "ssh_port": 22,
    "ssh_user": "root",
    "ssh_password": "password",
    "agent_port": 8080,
    "is_local": true
}

### update node
POST http://{{HOST}}/api/node/update
Content-Type: application/json

{
    "id": 1,
    "name": "test1",
    "address": "127.0.0.1",
    "port": 8080,
    "is_local": true
}

### delete node
POST http://{{HOST}}/api/node/delete
Content-Type: application/json

{
    "id": 1
}

### get node
POST http://{{HOST}}/api/node/get
Content-Type: application/json

{
    "id": 1
}


### get docker info
GET http://{{HOST}}/api/docker/info
Content-Type: application/json
X-Node-ID: 1

### list application
POST http://{{HOST}}/api/application/list
Content-Type: application/json

{
  "page": 1,
  "page_size": 10
}

### add application
POST http://{{HOST}}/api/application/add
Content-Type: application/json

{
  "id": 0,
  "name": "daaaaa",
  "display": "qwwww",
  "description": "qwwwww",
  "version": "qwwww",
  "icon": "lucide:app-window",
  "qa": [
    {
      "name": "wqq",
      "value": "ddd",
      "type": "text",
      "default_value": "ww",
      "required": false,
      "description": "qwwww"
    }
  ],
  "metadata": [
    {
      "name": "qqq",
      "properties": {
        "www": "eee"
      }
    }
  ]
}

### update application
POST http://{{HOST}}/api/application/update
Content-Type: application/json

{
  "id": 1,
  "name": "daaaaa",
  "display": "",
  "description": "qwwwww",
  "version": "qwwww",
  "icon": "lucide:app-window",
  "qa": [
    {
      "name": "wqq",
      "value": "ddd",
      "type": "text",
      "default_value": "ddd",
      "required": true,
      "description": "qwwww"
    }
  ],
  "metadata": [
    {
      "name": "qqq",
      "properties": {
        "www": "eee"
      }
    }
  ]
}